name: "Check if external data changed"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */6 * * *"

jobs:
  flatpak-data-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: nalsai/myflatpaks/.external-data-checker@main
        env:
          GITHUB_TOKEN: ${{ secrets.NALSAIBOT_TOKEN }}
